### ISSUE TITLE
Permission to add a new Project

### ISSUE THREAD

**Issue by AM1CODES** [DSC-VIT-BHOPAL/Machine-Learning-Projects#11]
I have a project that i think would be a great addition to this repo. If you  permit, i would like to make a PR.

**Comment by amansharma2910** [comment]
Can you elaborate a bit more on this project and what it is about? A few screenshots will be appreciated too. Thanks.

**Comment by AM1CODES** [comment]
Alright. So its a project in which we make use of data about campus placements to predict whether a candidate who's appearing for placement will be selected or not. It's a classification type problem so i made use of Logistic regression, SVM and KNN in order to see which of these performed the best and tried to predict the output.
![result1](https://user-images.githubusercontent.com/52394145/96346930-0e9d0680-10bc-11eb-9698-f44e02e59470.PNG)
![result2](https://user-images.githubusercontent.com/52394145/96346931-0f359d00-10bc-11eb-8e8e-0e8740a84abc.PNG)

These are a few results that the model gave. Let me know if you need some more information. I will also attach the data set along with the model and results so that it's easier for others to work with it.

**Comment by amansharma2910** [comment]
Seems good. Go ahead and raise a PR.

**Comment by AM1CODES** [comment]
On it.
