### ISSUE TITLE
Complete beginner exercises in Cervical Cancer notebook.

### ISSUE THREAD

**Issue by amansharma2910** [DSC-VIT-BHOPAL/Machine-Learning-Projects#13]
There are several exercises at the end of the cervical cancer risk prediction notebook like this one: 
![image](https://user-images.githubusercontent.com/53087550/96364644-2c6c7900-1159-11eb-9dd8-2eae733c2daa.png)

Complete the exercises to learn and contribute to the project.

**Comment by aditya-chavda** [comment]
Can I work on this?

Also, shall I do separate pull requests for each exercise in the cervical cancer notebook?

**Comment by amansharma2910** [comment]
Sure @aditya-chavda. You can go ahead and work on this issue. 
Regarding pull requests, address as many exercises that you can in a single PR.

**Comment by Ani0202** [comment]
I have completed the exercises and made a PR.  Pls check it
