### ISSUE TITLE
New Project Submission

### ISSUE THREAD

**Issue by AM1CODES** [DSC-VIT-BHOPAL/Machine-Learning-Projects#24]
I recently participated in Kaggle 2020 Survey analysis competition and the notebook contains intensive EDA along  with the highlighted points that we could get from analysing the data. I request your permission to make a PR in order to add the project. Do let me know if you need any further information.

**Comment by amansharma2910** [comment]
You can go ahead and make the PR

**Comment by AM1CODES** [comment]
Sure. Thank  You.

**Comment by AM1CODES** [comment]
@amansharma2910 Just created a PR for the project. Kindly look into it. If you  need some extra details, kindly let me know.
