### ISSUE TITLE
Permission request to add a new project.

### ISSUE THREAD

**Issue by AndroAvi** [DSC-VIT-BHOPAL/Machine-Learning-Projects#26]
I've recently created and worked on demonstrating the basic elements in the workflow of a typical supervised machine learning project, including exploratory analysis, data wrangling, scaling for model optimization, and automating model training using pipelines. I've used the "Titanic Survival Dataset" for the said analysis.

With your permission, I'd like to make a PR to add the same. Ping me if you need details.

**Comment by amansharma2910** [comment]
You can go ahead and make a PR. I'll have a look at the code.
