### ISSUE TITLE
Improve documentation for Book Recommender System project.

### ISSUE THREAD

**Issue by amansharma2910** [DSC-VIT-BHOPAL/Machine-Learning-Projects#5]
Improve the project documentation by adding information regarding the model architectures, observations, conclusions, etc.

**Comment by AM1CODES** [comment]
Made the changes in the documentation, added the objective of the project, the steps involved in making it, tools used and results along with the images. Requesting your permission to make a PR. @amansharma2910

**Comment by amansharma2910** [comment]
Permission granted. Go ahead and make the PR

**Comment by AM1CODES** [comment]
@amansharma2910 PR made.

**Comment by amansharma2910** [comment]
Thanks for your contribution. Your changes have been merged.
